name: Coinector
description: Coinecting to coimunity...

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 4.0.1+253866

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  hovering: ^1.0.4
  firebase_core: ^1.10.6
  flutter_easyrefresh: ^2.2.1
  fluttertoast: ^8.0.8
  permission_handler: ^8.3.0
  synchronized: ^3.0.0
  awesome_dialog: ^2.1.2
  flutter_phoenix: ^1.0.0
  loading_animations: ^2.2.0
  shared_preferences: ^2.0.11
  share: ^2.0.4
  dio: ^4.0.4
  responsive_framework: ^0.1.5
  connectivity: ^3.0.6
  in_app_review: ^2.0.3
  transparent_image: ^2.0.0
  smooth_star_rating: ^1.1.1
  google_maps_flutter: ^2.1.1
  google_maps_flutter_web: 0.3.2
  url_launcher: ^6.0.17
  flutter_i18n: ^0.31.0
  geolocator: ^8.0.1
  crypto: ^3.0.1
  path_provider: ^2.0.8
  #device_preview: ^0.4.8
  #desktop_window: ^0.3.0
  #js: ^0.6.2
  #http: ^0.12.2
  #onesignal_flutter: ^2.6.1
  #flutter_web_plugins:
  # sdk: flutter
  #firebase_core_web: 0.2.0
  #firebase_picture_uploader: ^1.3.1
  #image_picker: ^0.8.4+4
  #image_picker_for_web: 0.1.0+2
  #github: 7.0.3
  #firebase_analytics: ^8.3.4
  #carousel_slider: 2.3.1
  #flutter_web_scrollbar: ^0.0.3
  #bitbox: ^0.0.5
  #bch_wallet: ^0.0.3
  #material_floating_search_bar: ^0.2.2
  #country_code_picker: ^1.6.0
  #place_picker: ^0.9.9
  #after_init: ^0.1.2
  #universal_html: 1.2.3
  #platform_detect: ^1.4.0
  #fluro: ^1.7.6
  #firebase_messaging: ^11.2.0
  #firebase_core: ^0.4.0+5
  #firebase_crashlytics: ^2.4.0
  #flutter_advanced_networkimage: any
  #launch_review: 2.0.0
  #flutter_crashlytics: 1.0.0
  #clipboard_manager: ^0.0.4
  #flutter_typeahead: ^1.4.0
  #confetti: ^0.5.4+1
  #dio_http_cache

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

#flutter_icons:
#  image_path: "assets/web_hi_res_512.png"
#  android: true
#  ios: true

#this override is necessary for launcher icon generation plugin
#dependency_overrides:
 # image: 2.0.7
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

#ALREADY INSIDE i18n plugin
#flutter_localizations:
 ##   sdk: flutter

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/flutter_i18n/
    - assets/placeholder640x480.jpg
    - assets/addr.json
    - assets/am.json
    - assets/am-ven.json
    - assets/am-ven-car.json
    - assets/as.json
    - assets/as-jap.json
    - assets/au.json
    - assets/e.json
    - assets/e-spa.json
    - assets/placesId.json
    - assets/places.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: true
