name: Coinector
description: Coinnect the coimunity.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.7+24

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  #place_picker: ^0.9.9
  fluttertoast: ^3.1.0
  #flutter_launcher_icons: ^0.7.0
  permission_handler: ^3.1.0
  synchronized: ^2.1.0
  firebase_messaging: ^5.0.3
  #permission: ^0.1.1
  #flutter_advanced_networkimage: any
  #launch_review: 2.0.0
  #flutter_crashlytics: 1.0.0
  firebase_core: ^0.4.0+5
  clipboard_manager: ^0.0.4
  #flutter_typeahead: ^1.4.0
  shared_preferences: ^0.5.3+1
  dio: ^3.0.9
  firebase_crashlytics: ^0.0.4+5
  transparent_image: ^1.0.0
  smooth_star_rating: ^1.0.3
  google_maps_flutter: ^0.5.28+1
  url_launcher: ^5.0.3
  flutter_i18n: ^0.6.3
  geolocator: ^5.0.1
  crypto: ^2.0.6
  path_provider: ^1.1.0
  onesignal_flutter: ^2.1.0
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

#flutter_icons:
#  image_path: "assets/web_hi_res_512.png"
#  android: true
#  ios: true

#this override is necessary for launcher icon generation plugin
#dependency_overrides:
 # image: 2.0.7
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

#ALREADY INSIDE i18n plugin
#flutter_localizations:
 ##   sdk: flutter

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/flutter_i18n/
    - assets/placeholder640x480.jpg
    - assets/addr.json
    - assets/am.json
    - assets/am-ven.json
    - assets/am-ven-car.json
    - assets/as.json
    - assets/as-jap.json
    - assets/au.json
    - assets/e.json
    - assets/e-spa.json
    - assets/placesId.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
